name: Stale PR Management

on:
  schedule:
    - cron: '0 0 * * 6'  # Runs weekly on Saturday at midnight

permissions:
  pull-requests: write
  issues: write

jobs:
  check_stale_prs:
    name: Check and Manage Stale PRs
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Process PRs
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const now = new Date();

            // Helper function to calculate a date before now
            function getDateBeforeNow(days = 0) {
              const date = new Date(now);
              date.setDate(date.getDate() - days);
              return date;
            }

            // Inactivity thresholds
            const threeMonthsBeforeNow = getDateBeforeNow(90);
            const fourMonthsBeforeNow = getDateBeforeNow(120);
            const oneWeekBeforeNow = getDateBeforeNow(7);

            // Helper function to paginate open PRs
            async function getAllOpenPRs() {
              let allPRs = [];
              let page = 1;
              const perPage = 100;
              while (true) {
                const { data: prs } = await github.rest.pulls.list({
                  owner,
                  repo,
                  state: "open",
                  per_page: perPage,
                  page: page
                });
                if (prs.length === 0) break;
                allPRs = allPRs.concat(prs);
                page++;
              }
              return allPRs;
            }

            async function processPRs() {
              const pullRequests = await getAllOpenPRs();
              console.log(`Total PRs fetched: ${pullRequests.length}`);
             
              for (const pr of pullRequests) {
                const prNumber = pr.number;
                const updatedAt = new Date(pr.updated_at);

                // Fetch PR labels
                const { data: labels } = await github.rest.issues.listLabelsOnIssue({
                  owner,
                  repo,
                  issue_number: prNumber
                });
                const labelNames = labels.map(l => l.name);

                // Fetch PR timeline to check for contributor activity (comments & events)
                const { data: timeline } = await github.rest.issues.listEvents({
                  owner,
                  repo,
                  issue_number: prNumber,
                  per_page: 100
                });
                const lastContributorActivity = timeline
                  .filter(event => event.actor && event.actor.type === "User")
                  .map(event => new Date(event.created_at))
                  .sort((a, b) => b - a)[0] || updatedAt;

                // Rule 1: 3 months inactivity â†’ Add reminder comment
                if (lastContributorActivity < threeMonthsBeforeNow && !labelNames.includes('stale')) {
                  await github.rest.issues.createComment({
                    owner,
                    repo,
                    issue_number: prNumber,
                    body: `ðŸ‘‹ This PR has been inactive for 3 months. Are you still working on this? If you're facing issues, please update the PR or discuss them in our forum.`
                  });
                  console.log(`PR #${prNumber} received a reminder comment.`);
                }

                // Rule 2: 4 months inactivity â†’ Add warning comment
                if (lastContributorActivity < fourMonthsBeforeNow && !labelNames.includes('stale')) {
                  await github.rest.issues.createComment({
                    owner,
                    repo,
                    issue_number: prNumber,
                    body: `âš ï¸ This PR has been inactive for 4 months. If no action is taken soon, it may be marked as stale and closed.`
                  });
                  console.log(`PR #${prNumber} received a warning comment.`);
                }

                // Rule 3: 1 week inactivity after warning â†’ Mark as stale & close
                if (lastContributorActivity < oneWeekBeforeNow && !labelNames.includes('stale')) {
                  // Add the stale label first
                  await github.rest.issues.addLabels({
                    owner,
                    repo,
                    issue_number: prNumber,
                    labels: ['stale']
                  });
                  console.log(`PR #${prNumber} marked as stale.`);

                  // Then add the closing comment
                  await github.rest.issues.createComment({
                    owner,
                    repo,
                    issue_number: prNumber,
                    body: `ðŸš¨ This PR has been inactive for too long. Closing due to inactivity. If you are still working on this, please reopen the PR or ask a maintainer for help.`
                  });

                  // Finally, close the PR
                  await github.rest.pulls.update({
                    owner,
                    repo,
                    pull_number: prNumber,
                    state: "closed"
                  });
                  console.log(`PR #${prNumber} marked as stale and closed.`);
                }
              }
            }

            await processPRs();
